version: "3.3"

services:
  database:
    image: postgres
    restart: on-failure
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: devpro
      POSTGRES_USER: devpron
      POSTGRES_PORT: 5432
      POSTGRES_DB: devpron_db
    ports:
      - "5432:5432"
    expose:
      - "5432"
